### ISSUE TITLE
Dashbord shows wrong unit

### ISSUE THREAD

**Issue by dirkwa** [Saillogger/signalk-windy-plugin#11]
I am sailing atm and noticed that windy plugin shows in the dashboard kt. That values are too low. In the data browser I see m/s.

![image](https://github.com/user-attachments/assets/ec0f0c80-19d7-4d94-ad57-81f2ef4206c3)

![image](https://github.com/user-attachments/assets/f5f71880-2bad-4bc4-8ca0-9f10405c8f36)

**Comment by dirkwa** [comment]
That values are also sent to the windy server.

![image](https://github.com/user-attachments/assets/bb2b957b-9ae5-4f67-90a3-3e01efdb632b)

**Comment by dirkwa** [comment]
Could it be that you need to convert m/s to kt here?

case 'environment.wind.speedOverGround':
        let speed = value.toFixed(2);
        speed = parseFloat(speed);
	if ((windGust == null) || (speed > windGust)) {
	  windGust = speed;
	}
	windSpeed.push(speed);

**Comment by dirkwa** [comment]
Just saw that windy expects m/s in their API

https://community.windy.com/topic/8168/report-your-weather-station-data-to-windy/2

So must be a typo than for the dashboard.

**Comment by dirkwa** [comment]
I assume it is line #126
`      	statusMessage += `Wind speed is ${currentWindSpeed}kts and gust is ${windGust}kts.`;`

**Comment by dirkwa** [comment]
Hi,

is this project still maintained?

**Comment by itemir** [comment]
This should be knots, m/s is a the right unit for dealing with data but it makes less sense for boaters. Fixed in 1.2.0 release.
